/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ttdesign;


import FireData.Firedata;
import FireData.ProfessorInfo;

import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.ExecutionException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *z
 * @author imran
 */
public class SubjectData extends javax.swing.JFrame {
    String year, semester;
    ArrayList<String> model;
    ArrayList<ProfessorInfo> profModel;
    Firedata firedata;
    /**
     * Creates new form SubjectDatas
     */
    public SubjectData() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = new ArrayList<String>();
        try {
            firedata = new Firedata();
            profModel = firedata.retriveProfessor();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        jComboBoxSEM.setVisible(false);
     }
    
    public void initialProfessor(){
        profModel.forEach(z -> {
            String x = z.getProfName();
            jComboBoxPROF1.addItem(x);
            jComboBoxPROF2.addItem(x);
            jComboBoxPROF3.addItem(x);
            jComboBoxPROF4.addItem(x);
            jComboBoxPROF5.addItem(x);
            jComboBoxPROF_LAB1.addItem(x);
            jComboBoxPROF_LAB2.addItem(x);
            jComboBoxPROF_LAB3.addItem(x);
            jComboBoxPROF_LAB4.addItem(x);
            jComboBoxPROF_LAB5.addItem(x);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxYEAR = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxSEM = new javax.swing.JComboBox<>();
        jLabelSUB_1 = new javax.swing.JLabel();
        jComboBoxPROF1 = new javax.swing.JComboBox<>();
        jLabelSUB_2 = new javax.swing.JLabel();
        jComboBoxPROF2 = new javax.swing.JComboBox<>();
        jComboBoxPROF3 = new javax.swing.JComboBox<>();
        jComboBoxPROF4 = new javax.swing.JComboBox<>();
        jLabelSUB_4 = new javax.swing.JLabel();
        jComboBoxPROF5 = new javax.swing.JComboBox<>();
        jLabelSUB_5 = new javax.swing.JLabel();
        jComboBoxWEEK1 = new javax.swing.JComboBox<>();
        jComboBoxWEEK2 = new javax.swing.JComboBox<>();
        jComboBoxWEEK3 = new javax.swing.JComboBox<>();
        jComboBoxWEEK4 = new javax.swing.JComboBox<>();
        jComboBoxWEEK5 = new javax.swing.JComboBox<>();
        jLabelLAB_1 = new javax.swing.JLabel();
        jComboBoxPROF_LAB1 = new javax.swing.JComboBox<>();
        jComboBoxWEEK_LAB1 = new javax.swing.JComboBox<>();
        jLabelLAB_2 = new javax.swing.JLabel();
        jComboBoxPROF_LAB2 = new javax.swing.JComboBox<>();
        jComboBoxWEEK_LAB2 = new javax.swing.JComboBox<>();
        jLabelLAB_3 = new javax.swing.JLabel();
        jComboBoxPROF_LAB3 = new javax.swing.JComboBox<>();
        jComboBoxWEEK_LAB3 = new javax.swing.JComboBox<>();
        jLabelLAB_4 = new javax.swing.JLabel();
        jComboBoxPROF_LAB4 = new javax.swing.JComboBox<>();
        jComboBoxWEEK_LAB4 = new javax.swing.JComboBox<>();
        jLabelLAB_5 = new javax.swing.JLabel();
        jComboBoxPROF_LAB5 = new javax.swing.JComboBox<>();
        jComboBoxWEEK_LAB5 = new javax.swing.JComboBox<>();
        jButtonSAVE = new javax.swing.JButton();
        jButtonLogin1 = new javax.swing.JButton();
        jLabelSUB_3 = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabelClose.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setText("x");
        jLabelClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FILL THE INFOMATION");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelMin.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel2)
                                        .addContainerGap(249, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelClose)
                                        .addComponent(jLabelMin))
                                .addGap(0, 24, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 250));

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("YEAR:");

        jComboBoxYEAR.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxYEAR.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxYEAR.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxYEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SECOND YEAR", "THIRD YEAR", "FOURTH YEAR" }));
        jComboBoxYEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxYEARActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("SEMESTER:");

        jComboBoxSEM.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxSEM.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxSEM.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxSEM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRST", "SECOND" }));
        jComboBoxSEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSEMActionPerformed(evt);
            }
        });

        jLabelSUB_1.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelSUB_1.setForeground(new java.awt.Color(236, 240, 241));
        jLabelSUB_1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSUB_1.setText("SUBJECT_1");

        jComboBoxPROF1.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF1.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxPROF1.setName(""); // NOI18N
        jComboBoxPROF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPROF1ActionPerformed(evt);
            }
        });

        jLabelSUB_2.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelSUB_2.setForeground(new java.awt.Color(236, 240, 241));
        jLabelSUB_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSUB_2.setText("SUBJECT_2");

        jComboBoxPROF2.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF2.setForeground(new java.awt.Color(236, 240, 241));

        jComboBoxPROF3.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF3.setForeground(new java.awt.Color(236, 240, 241));

        jComboBoxPROF4.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF4.setForeground(new java.awt.Color(236, 240, 241));

        jLabelSUB_4.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelSUB_4.setForeground(new java.awt.Color(236, 240, 241));
        jLabelSUB_4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSUB_4.setText("SUBJECT_4");

        jComboBoxPROF5.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF5.setForeground(new java.awt.Color(236, 240, 241));

        jLabelSUB_5.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelSUB_5.setForeground(new java.awt.Color(236, 240, 241));
        jLabelSUB_5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSUB_5.setText("SUBJECT_5");

        jComboBoxWEEK1.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK1.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoxWEEK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWEEK1ActionPerformed(evt);
            }
        });

        jComboBoxWEEK2.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK2.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jComboBoxWEEK3.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK3.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jComboBoxWEEK4.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK4.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jComboBoxWEEK5.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK5.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabelLAB_1.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelLAB_1.setForeground(new java.awt.Color(236, 240, 241));
        jLabelLAB_1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLAB_1.setText("LAB_1");

        jComboBoxPROF_LAB1.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF_LAB1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF_LAB1.setForeground(new java.awt.Color(236, 240, 241));

        jComboBoxWEEK_LAB1.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK_LAB1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK_LAB1.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK_LAB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabelLAB_2.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelLAB_2.setForeground(new java.awt.Color(236, 240, 241));
        jLabelLAB_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLAB_2.setText("LAB_2");

        jComboBoxPROF_LAB2.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF_LAB2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF_LAB2.setForeground(new java.awt.Color(236, 240, 241));

        jComboBoxWEEK_LAB2.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK_LAB2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK_LAB2.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK_LAB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoxWEEK_LAB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWEEK_LAB2ActionPerformed(evt);
            }
        });

        jLabelLAB_3.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelLAB_3.setForeground(new java.awt.Color(236, 240, 241));
        jLabelLAB_3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLAB_3.setText("LAB_3");

        jComboBoxPROF_LAB3.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF_LAB3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF_LAB3.setForeground(new java.awt.Color(236, 240, 241));

        jComboBoxWEEK_LAB3.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK_LAB3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK_LAB3.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK_LAB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabelLAB_4.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelLAB_4.setForeground(new java.awt.Color(236, 240, 241));
        jLabelLAB_4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLAB_4.setText("LAB_4");

        jComboBoxPROF_LAB4.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF_LAB4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF_LAB4.setForeground(new java.awt.Color(236, 240, 241));

        jComboBoxWEEK_LAB4.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK_LAB4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK_LAB4.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK_LAB4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabelLAB_5.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelLAB_5.setForeground(new java.awt.Color(236, 240, 241));
        jLabelLAB_5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLAB_5.setText("LAB_5");

        jComboBoxPROF_LAB5.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxPROF_LAB5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxPROF_LAB5.setForeground(new java.awt.Color(236, 240, 241));

        jComboBoxWEEK_LAB5.setBackground(new java.awt.Color(44, 62, 80));
        jComboBoxWEEK_LAB5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxWEEK_LAB5.setForeground(new java.awt.Color(236, 240, 241));
        jComboBoxWEEK_LAB5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jButtonSAVE.setBackground(new java.awt.Color(34, 167, 240));
        jButtonSAVE.setText("SAVE");
        jButtonSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAVEActionPerformed(evt);
            }
        });

        jButtonLogin1.setBackground(new java.awt.Color(34, 167, 240));
        jButtonLogin1.setText("CLEAR");

        jLabelSUB_3.setFont(new java.awt.Font("DialogInput", 0, 17)); // NOI18N
        jLabelSUB_3.setForeground(new java.awt.Color(236, 240, 241));
        jLabelSUB_3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSUB_3.setText("SUBJECT_3");

        jButtonNext.setBackground(new java.awt.Color(34, 167, 240));
        jButtonNext.setText("->");

        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabelSUB_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addGap(22, 22, 22)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabelSUB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabelSUB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabelSUB_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jLabelSUB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addComponent(jLabelLAB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jLabelLAB_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabelLAB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabelLAB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabelLAB_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(39, 39, 39)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jComboBoxPROF4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                .addComponent(jComboBoxPROF2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 221, Short.MAX_VALUE)
                                                                                                .addComponent(jComboBoxPROF3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(jComboBoxPROF_LAB1, 0, 221, Short.MAX_VALUE)
                                                                                        .addComponent(jComboBoxPROF5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                                                                .addComponent(jButtonSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(26, 26, 26)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addComponent(jComboBoxWEEK5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                .addComponent(jButtonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jComboBoxWEEK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(jComboBoxWEEK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(jComboBoxWEEK3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(jComboBoxWEEK4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(jComboBoxWEEK_LAB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(jComboBoxWEEK_LAB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(jComboBoxWEEK_LAB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jComboBoxWEEK_LAB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(jComboBoxWEEK_LAB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(15, 15, 15))))))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(39, 39, 39)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jComboBoxPROF_LAB2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jComboBoxPROF_LAB3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jComboBoxPROF_LAB4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jComboBoxPROF_LAB5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(185, 185, 185)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBoxPROF1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(40, 40, 40)
                                                                        .addComponent(jComboBoxSEM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(40, 40, 40)
                                                                        .addComponent(jComboBoxYEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxYEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxSEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxPROF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxWEEK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxPROF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxWEEK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jComboBoxPROF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBoxWEEK3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 29, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jComboBoxPROF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBoxWEEK4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBoxWEEK5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(46, 46, 46)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jComboBoxPROF_LAB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jComboBoxWEEK_LAB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jComboBoxWEEK_LAB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jComboBoxPROF_LAB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jComboBoxWEEK_LAB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(21, 21, 21)
                                                .addComponent(jComboBoxWEEK_LAB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jComboBoxPROF_LAB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBoxWEEK_LAB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(46, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jButtonSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabelSUB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSUB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSUB_3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jLabelSUB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelSUB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxPROF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabelLAB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelLAB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelLAB_3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxPROF_LAB3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelLAB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxPROF_LAB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabelLAB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jComboBoxYEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxYEARActionPerformed
       year = jComboBoxYEAR.getItemAt(jComboBoxYEAR.getSelectedIndex());
        jComboBoxSEM.setVisible(true);
        switch(year){
                    case "SECOND YEAR":
                        jLabelSUB_1.setText("DSA");
                        jLabelSUB_2.setText("DM");
                        jLabelSUB_3.setText("COA");
                        jLabelSUB_4.setText("DELD");
                        jLabelSUB_5.setText("OOP");
                        jLabelLAB_1.setText("DSAL1");
                        jLabelLAB_2.setText("DSAL2");
                        jLabelLAB_3.setText("OOPL1");
                        jLabelLAB_4.setText("DELDL");
                        jLabelLAB_5.setText("SSL");
                        
                        jComboBoxWEEK1.setSelectedIndex(3);
                        jComboBoxWEEK2.setSelectedIndex(3);
                        jComboBoxWEEK3.setSelectedIndex(3);
                        jComboBoxWEEK4.setSelectedIndex(3);
                        jComboBoxWEEK5.setSelectedIndex(3);
                        jComboBoxWEEK_LAB1.setSelectedIndex(1);
                        jComboBoxWEEK_LAB2.setSelectedIndex(1);
                        jComboBoxWEEK_LAB3.setSelectedIndex(1);
                        jComboBoxWEEK_LAB4.setSelectedIndex(1);
                        jComboBoxWEEK_LAB5.setSelectedIndex(1);
                                
                    break;

                    case "THIRD YEAR":
                        jLabelSUB_1.setText("TOC");
                        jLabelSUB_2.setText("DBMS");
                        jLabelSUB_3.setText("SEPM");
                        jLabelSUB_4.setText("ISEE");
                        jLabelSUB_5.setText("CN");
                        jLabelLAB_1.setText("DBMSL1");
                        jLabelLAB_2.setText("DBMSL2");
                        jLabelLAB_3.setText("SDL1");
                        jLabelLAB_4.setText("SDL2");
                        jLabelLAB_5.setText("CNL");
                        
                        jComboBoxWEEK1.setSelectedIndex(2);
                        jComboBoxWEEK2.setSelectedIndex(2);
                        jComboBoxWEEK3.setSelectedIndex(2);
                        jComboBoxWEEK4.setSelectedIndex(2);
                        jComboBoxWEEK5.setSelectedIndex(3);
                        jComboBoxWEEK_LAB1.setSelectedIndex(1);
                        jComboBoxWEEK_LAB2.setSelectedIndex(1);
                        jComboBoxWEEK_LAB3.setSelectedIndex(1);
                        jComboBoxWEEK_LAB4.setSelectedIndex(1);
                        jComboBoxWEEK_LAB5.setSelectedIndex(1);
                        
                        break;

                    case "FOURTH YEAR":
                        jLabelSUB_1.setText("HPC");
                        jLabelSUB_2.setText("AI&R");
                        jLabelSUB_3.setText("EL1");
                        jLabelSUB_4.setText("EL2");
                        jLabelSUB_5.setText("DA");
                        jLabelLAB_1.setText("LP1A");
                        jLabelLAB_2.setText("LP1B");
                        jLabelLAB_3.setText("LP2A");
                        jLabelLAB_4.setText("LP2B");
                        jLabelLAB_5.setText("PWS");
                        
                        jComboBoxWEEK1.setSelectedIndex(3);
                        jComboBoxWEEK2.setSelectedIndex(2);
                        jComboBoxWEEK3.setSelectedIndex(2);
                        jComboBoxWEEK4.setSelectedIndex(2);
                        jComboBoxWEEK5.setSelectedIndex(2);
                        jComboBoxWEEK_LAB1.setSelectedIndex(1);
                        jComboBoxWEEK_LAB2.setSelectedIndex(1);
                        jComboBoxWEEK_LAB3.setSelectedIndex(1);
                        jComboBoxWEEK_LAB4.setSelectedIndex(1);
                        jComboBoxWEEK_LAB5.setSelectedIndex(1);
                        break;
                }
    }//GEN-LAST:event_jComboBoxYEARActionPerformed

    private void jComboBoxSEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSEMActionPerformed
       initialProfessor();
       semester = jComboBoxSEM.getItemAt(jComboBoxSEM.getSelectedIndex());
       setSubject();
    }//GEN-LAST:event_jComboBoxSEMActionPerformed

    private void jComboBoxWEEK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWEEK1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWEEK1ActionPerformed

    private void jComboBoxPROF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPROF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPROF1ActionPerformed

    private void jComboBoxWEEK_LAB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWEEK_LAB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWEEK_LAB2ActionPerformed

    private void jButtonSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAVEActionPerformed
        switch(year){
                    case "SECOND YEAR":
                        try {
                            firedata.deleteSE_SUBJECT();
                            firedata.addSE_SUBJECT( jLabelSUB_1.getText(),jComboBoxPROF1.getItemAt(jComboBoxPROF1.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK1.getItemAt(jComboBoxWEEK1.getSelectedIndex())), false);
                            firedata.addSE_SUBJECT( jLabelSUB_2.getText(),jComboBoxPROF2.getItemAt(jComboBoxPROF2.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK2.getItemAt(jComboBoxWEEK2.getSelectedIndex())), false);
                            firedata.addSE_SUBJECT( jLabelSUB_3.getText(),jComboBoxPROF3.getItemAt(jComboBoxPROF3.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK3.getItemAt(jComboBoxWEEK3.getSelectedIndex())), false);
                            firedata.addSE_SUBJECT( jLabelSUB_4.getText(),jComboBoxPROF4.getItemAt(jComboBoxPROF4.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK4.getItemAt(jComboBoxWEEK4.getSelectedIndex())), false);
                            firedata.addSE_SUBJECT( jLabelSUB_5.getText(),jComboBoxPROF5.getItemAt(jComboBoxPROF5.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK5.getItemAt(jComboBoxWEEK5.getSelectedIndex())), false);

                            firedata.addSE_SUBJECT( jLabelLAB_1.getText(), jComboBoxPROF_LAB1.getItemAt(jComboBoxPROF_LAB1.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB1.getItemAt(jComboBoxWEEK_LAB1.getSelectedIndex())), true);
                            firedata.addSE_SUBJECT(jLabelLAB_2.getText(), jComboBoxPROF_LAB2.getItemAt(jComboBoxPROF_LAB2.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB2.getItemAt(jComboBoxWEEK_LAB2.getSelectedIndex())), true);
                            firedata.addSE_SUBJECT( jLabelLAB_3.getText(), jComboBoxPROF_LAB3.getItemAt(jComboBoxPROF_LAB3.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB3.getItemAt(jComboBoxWEEK_LAB3.getSelectedIndex())), true);
                            firedata.addSE_SUBJECT( jLabelLAB_4.getText(), jComboBoxPROF_LAB4.getItemAt(jComboBoxPROF_LAB4.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB4.getItemAt(jComboBoxWEEK_LAB4.getSelectedIndex())), true);
                            firedata.addSE_SUBJECT( jLabelLAB_5.getText(), jComboBoxPROF_LAB5.getItemAt(jComboBoxPROF_LAB5.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB5.getItemAt(jComboBoxWEEK_LAB5.getSelectedIndex())), true);
                            JOptionPane.showMessageDialog(this,"Data Successfully Added");
                        } catch (Exception e) {
                            System.out.println(e.toString());
                        }
                        break;

                    case "THIRD YEAR":
                        try {
                            firedata.deleteTE_SUBJECT();
                            firedata.addTE_SUBJECT( jLabelSUB_1.getText(),jComboBoxPROF1.getItemAt(jComboBoxPROF1.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK1.getItemAt(jComboBoxWEEK1.getSelectedIndex())), false);
                            firedata.addTE_SUBJECT( jLabelSUB_2.getText(),jComboBoxPROF2.getItemAt(jComboBoxPROF2.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK2.getItemAt(jComboBoxWEEK2.getSelectedIndex())), false);
                            firedata.addTE_SUBJECT( jLabelSUB_3.getText(),jComboBoxPROF3.getItemAt(jComboBoxPROF3.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK3.getItemAt(jComboBoxWEEK3.getSelectedIndex())), false);
                            firedata.addTE_SUBJECT( jLabelSUB_4.getText(),jComboBoxPROF4.getItemAt(jComboBoxPROF4.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK4.getItemAt(jComboBoxWEEK4.getSelectedIndex())), false);
                            firedata.addTE_SUBJECT( jLabelSUB_5.getText(),jComboBoxPROF5.getItemAt(jComboBoxPROF5.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK5.getItemAt(jComboBoxWEEK5.getSelectedIndex())), false);

                            firedata.addTE_SUBJECT( jLabelLAB_1.getText(), jComboBoxPROF_LAB1.getItemAt(jComboBoxPROF_LAB1.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB1.getItemAt(jComboBoxWEEK_LAB1.getSelectedIndex())), true);
                            firedata.addTE_SUBJECT(jLabelLAB_2.getText(), jComboBoxPROF_LAB2.getItemAt(jComboBoxPROF_LAB2.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB2.getItemAt(jComboBoxWEEK_LAB2.getSelectedIndex())), true);
                            firedata.addTE_SUBJECT( jLabelLAB_3.getText(), jComboBoxPROF_LAB3.getItemAt(jComboBoxPROF_LAB3.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB3.getItemAt(jComboBoxWEEK_LAB3.getSelectedIndex())), true);
                            firedata.addTE_SUBJECT( jLabelLAB_4.getText(), jComboBoxPROF_LAB4.getItemAt(jComboBoxPROF_LAB4.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB4.getItemAt(jComboBoxWEEK_LAB4.getSelectedIndex())), true);
                            firedata.addTE_SUBJECT( jLabelLAB_5.getText(), jComboBoxPROF_LAB5.getItemAt(jComboBoxPROF_LAB5.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB5.getItemAt(jComboBoxWEEK_LAB5.getSelectedIndex())), true);
                            JOptionPane.showMessageDialog(this,"Data Successfully Added");
                        } catch (Exception e) {
                            System.out.println(e.toString());
                        }
                        break;

                    case "FOURTH YEAR":
                        try {
                            firedata.deleteBE_SUBJECT();
                            firedata.addBE_SUBJECT( jLabelSUB_1.getText(),jComboBoxPROF1.getItemAt(jComboBoxPROF1.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK1.getItemAt(jComboBoxWEEK1.getSelectedIndex())), false);
                            firedata.addBE_SUBJECT( jLabelSUB_2.getText(),jComboBoxPROF2.getItemAt(jComboBoxPROF2.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK2.getItemAt(jComboBoxWEEK2.getSelectedIndex())), false);
                            firedata.addBE_SUBJECT( jLabelSUB_3.getText(),jComboBoxPROF3.getItemAt(jComboBoxPROF3.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK3.getItemAt(jComboBoxWEEK3.getSelectedIndex())), false);
                            firedata.addBE_SUBJECT( jLabelSUB_4.getText(),jComboBoxPROF4.getItemAt(jComboBoxPROF4.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK4.getItemAt(jComboBoxWEEK4.getSelectedIndex())), false);
                            firedata.addBE_SUBJECT( jLabelSUB_5.getText(),jComboBoxPROF5.getItemAt(jComboBoxPROF5.getSelectedIndex()),
                                    Integer.parseInt(jComboBoxWEEK5.getItemAt(jComboBoxWEEK5.getSelectedIndex())), false);

                            firedata.addBE_SUBJECT( jLabelLAB_1.getText(), jComboBoxPROF_LAB1.getItemAt(jComboBoxPROF_LAB1.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB1.getItemAt(jComboBoxWEEK_LAB1.getSelectedIndex())), true);
                            firedata.addBE_SUBJECT(jLabelLAB_2.getText(), jComboBoxPROF_LAB2.getItemAt(jComboBoxPROF_LAB2.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB2.getItemAt(jComboBoxWEEK_LAB2.getSelectedIndex())), true);
                            firedata.addBE_SUBJECT( jLabelLAB_3.getText(), jComboBoxPROF_LAB3.getItemAt(jComboBoxPROF_LAB3.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB3.getItemAt(jComboBoxWEEK_LAB3.getSelectedIndex())), true);
                            firedata.addBE_SUBJECT( jLabelLAB_4.getText(), jComboBoxPROF_LAB4.getItemAt(jComboBoxPROF_LAB4.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB4.getItemAt(jComboBoxWEEK_LAB4.getSelectedIndex())), true);
                            firedata.addBE_SUBJECT( jLabelLAB_5.getText(), jComboBoxPROF_LAB5.getItemAt(jComboBoxPROF_LAB5.getSelectedIndex()).toString(),
                                    Integer.parseInt(jComboBoxWEEK_LAB5.getItemAt(jComboBoxWEEK_LAB5.getSelectedIndex())), true);
                            JOptionPane.showMessageDialog(this,"Data Successfully Added");
                        } catch (Exception e) {
                            System.out.println(e.toString());
                        }
                             break;
                }
    }//GEN-LAST:event_jButtonSAVEActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {
        SuffleTimetable loginForm  =  new SuffleTimetable();
        loginForm.setVisible(true);
        loginForm.pack();
        loginForm.setLocationRelativeTo(null);
        loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }

    void setSubject(){
        switch(semester){
            case "FIRST":
                switch(year){
                    case "SECOND YEAR":
                        jLabelSUB_1.setText("DSA");
                        jLabelSUB_2.setText("DM");
                        jLabelSUB_3.setText("COA");
                        jLabelSUB_4.setText("DELD");
                        jLabelSUB_5.setText("OOP");
                        jLabelLAB_1.setText("DSAL1");
                        jLabelLAB_2.setText("DSAL2");
                        jLabelLAB_3.setText("OOPL1");
                        jLabelLAB_4.setText("DELDL");
                        jLabelLAB_5.setText("SSL");
                        
                        jComboBoxWEEK1.setSelectedIndex(3);
                        jComboBoxWEEK2.setSelectedIndex(3);
                        jComboBoxWEEK3.setSelectedIndex(3);
                        jComboBoxWEEK4.setSelectedIndex(3);
                        jComboBoxWEEK5.setSelectedIndex(3);
                        jComboBoxWEEK_LAB1.setSelectedIndex(1);
                        jComboBoxWEEK_LAB2.setSelectedIndex(1);
                        jComboBoxWEEK_LAB3.setSelectedIndex(1);
                        jComboBoxWEEK_LAB4.setSelectedIndex(1);
                        jComboBoxWEEK_LAB5.setSelectedIndex(1);
                                
                    break;

                    case "THIRD YEAR":
                        jLabelSUB_1.setText("TOC");
                        jLabelSUB_2.setText("DBMS");
                        jLabelSUB_3.setText("SEPM");
                        jLabelSUB_4.setText("ISEE");
                        jLabelSUB_5.setText("CN");
                        jLabelLAB_1.setText("DBMSL1");
                        jLabelLAB_2.setText("DBMSL2");
                        jLabelLAB_3.setText("SDL1");
                        jLabelLAB_4.setText("SDL2");
                        jLabelLAB_5.setText("CNL");
                        
                        jComboBoxWEEK1.setSelectedIndex(3);
                        jComboBoxWEEK2.setSelectedIndex(3);
                        jComboBoxWEEK3.setSelectedIndex(2);
                        jComboBoxWEEK4.setSelectedIndex(2);
                        jComboBoxWEEK5.setSelectedIndex(3);
                        jComboBoxWEEK_LAB1.setSelectedIndex(1);
                        jComboBoxWEEK_LAB2.setSelectedIndex(1);
                        jComboBoxWEEK_LAB3.setSelectedIndex(1);
                        jComboBoxWEEK_LAB4.setSelectedIndex(1);
                        jComboBoxWEEK_LAB5.setSelectedIndex(1);
                        
                        break;

                    case "FOURTH YEAR":
                        jLabelSUB_1.setText("HPC");
                        jLabelSUB_2.setText("AI&R");
                        jLabelSUB_3.setText("EL1");
                        jLabelSUB_4.setText("EL2");
                        jLabelSUB_5.setText("DA");
                        jLabelLAB_1.setText("LP1A");
                        jLabelLAB_2.setText("LP1B");
                        jLabelLAB_3.setText("LP2A");
                        jLabelLAB_4.setText("LP2B");
                        jLabelLAB_5.setText("PWS");
                        
                        jComboBoxWEEK1.setSelectedIndex(3);
                        jComboBoxWEEK2.setSelectedIndex(2);
                        jComboBoxWEEK3.setSelectedIndex(2);
                        jComboBoxWEEK4.setSelectedIndex(2);
                        jComboBoxWEEK5.setSelectedIndex(2);
                        jComboBoxWEEK_LAB1.setSelectedIndex(1);
                        jComboBoxWEEK_LAB2.setSelectedIndex(1);
                        jComboBoxWEEK_LAB3.setSelectedIndex(1);
                        jComboBoxWEEK_LAB4.setSelectedIndex(1);
                        jComboBoxWEEK_LAB5.setSelectedIndex(1);
                        break;
                }
                break;
                
            case "SECOND":
                switch(year){
                    case "SECOND YEAR":
                        jLabelSUB_1.setText("EM3");
                        jLabelSUB_2.setText("ADS");
                        jLabelSUB_3.setText("MP");
                        jLabelSUB_4.setText("CG");
                        jLabelSUB_5.setText("PPL");
                        jLabelLAB_1.setText("EM3L");
                        jLabelLAB_2.setText("ADSL1");
                        jLabelLAB_3.setText("MPL");
                        jLabelLAB_4.setText("CGL");
                        jLabelLAB_5.setText("ADSL2");
                        
                        jComboBoxWEEK1.setSelectedIndex(3);
                        jComboBoxWEEK2.setSelectedIndex(3);
                        jComboBoxWEEK3.setSelectedIndex(3);
                        jComboBoxWEEK4.setSelectedIndex(3);
                        jComboBoxWEEK5.setSelectedIndex(2);
                        jComboBoxWEEK_LAB1.setSelectedIndex(1);
                        jComboBoxWEEK_LAB2.setSelectedIndex(1);
                        jComboBoxWEEK_LAB3.setSelectedIndex(1);
                        jComboBoxWEEK_LAB4.setSelectedIndex(1);
                        jComboBoxWEEK_LAB5.setSelectedIndex(1);
                    break;

                    case "THIRD YEAR":
                         jLabelSUB_1.setText("DAA");
                        jLabelSUB_2.setText("SP&OS");
                        jLabelSUB_3.setText("ES&IOT");
                        jLabelSUB_4.setText("SMD");
                        jLabelSUB_5.setText("WT");
                        jLabelLAB_1.setText("WTL");
                        jLabelLAB_2.setText("SP&OSL1");
                        jLabelLAB_3.setText("ES&IOTL");
                        jLabelLAB_4.setText("SP&OSL2");
                        jLabelLAB_5.setText("STC");
                        
                        jComboBoxWEEK1.setSelectedIndex(3);
                        jComboBoxWEEK2.setSelectedIndex(3);
                        jComboBoxWEEK3.setSelectedIndex(3);
                        jComboBoxWEEK4.setSelectedIndex(2);
                        jComboBoxWEEK5.setSelectedIndex(2);
                        jComboBoxWEEK_LAB1.setSelectedIndex(1);
                        jComboBoxWEEK_LAB2.setSelectedIndex(1);
                        jComboBoxWEEK_LAB3.setSelectedIndex(1);
                        jComboBoxWEEK_LAB4.setSelectedIndex(1);
                        jComboBoxWEEK_LAB5.setSelectedIndex(1);
                        break;

                    case "FOURTH YEAR":
                         jLabelSUB_1.setText("ML");
                        jLabelSUB_2.setText("ICS");
                        jLabelSUB_3.setText("EL3");
                        jLabelSUB_4.setText("EL4");
                        jLabelSUB_5.setText("PSW");
                        jLabelLAB_1.setText("LP3A");
                        jLabelLAB_2.setText("LP3B");
                        jLabelLAB_3.setText("LP4A");
                        jLabelLAB_4.setText("LP4B");
                        jLabelLAB_5.setText("PSWL");
                        
                        jComboBoxWEEK1.setSelectedIndex(2);
                        jComboBoxWEEK2.setSelectedIndex(2);
                        jComboBoxWEEK3.setSelectedIndex(2);
                        jComboBoxWEEK4.setSelectedIndex(2);
                        jComboBoxWEEK5.setSelectedIndex(4);
                        jComboBoxWEEK_LAB1.setSelectedIndex(1);
                        jComboBoxWEEK_LAB2.setSelectedIndex(1);
                        jComboBoxWEEK_LAB3.setSelectedIndex(1);
                        jComboBoxWEEK_LAB4.setSelectedIndex(1);
                        jComboBoxWEEK_LAB5.setSelectedIndex(1);
                        break;
                }
                break;
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin1;
    private javax.swing.JButton jButtonSAVE;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JComboBox<String> jComboBoxPROF1;
    private javax.swing.JComboBox<String> jComboBoxPROF2;
    private javax.swing.JComboBox<String> jComboBoxPROF3;
    private javax.swing.JComboBox<String> jComboBoxPROF4;
    private javax.swing.JComboBox<String> jComboBoxPROF5;
    private javax.swing.JComboBox<String> jComboBoxPROF_LAB1;
    private javax.swing.JComboBox<String> jComboBoxPROF_LAB2;
    private javax.swing.JComboBox<String> jComboBoxPROF_LAB3;
    private javax.swing.JComboBox<String> jComboBoxPROF_LAB4;
    private javax.swing.JComboBox<String> jComboBoxPROF_LAB5;
    private javax.swing.JComboBox<String> jComboBoxSEM;
    private javax.swing.JComboBox<String> jComboBoxWEEK1;
    private javax.swing.JComboBox<String> jComboBoxWEEK2;
    private javax.swing.JComboBox<String> jComboBoxWEEK3;
    private javax.swing.JComboBox<String> jComboBoxWEEK4;
    private javax.swing.JComboBox<String> jComboBoxWEEK5;
    private javax.swing.JComboBox<String> jComboBoxWEEK_LAB1;
    private javax.swing.JComboBox<String> jComboBoxWEEK_LAB2;
    private javax.swing.JComboBox<String> jComboBoxWEEK_LAB3;
    private javax.swing.JComboBox<String> jComboBoxWEEK_LAB4;
    private javax.swing.JComboBox<String> jComboBoxWEEK_LAB5;
    private javax.swing.JComboBox<String> jComboBoxYEAR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelLAB_1;
    private javax.swing.JLabel jLabelLAB_2;
    private javax.swing.JLabel jLabelLAB_3;
    private javax.swing.JLabel jLabelLAB_4;
    private javax.swing.JLabel jLabelLAB_5;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelSUB_1;
    private javax.swing.JLabel jLabelSUB_2;
    private javax.swing.JLabel jLabelSUB_3;
    private javax.swing.JLabel jLabelSUB_4;
    private javax.swing.JLabel jLabelSUB_5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
